# Generated by Django 2.2.12 on 2020-07-15 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegisterModel',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('contact_no', models.IntegerField(unique=True)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StudentEnrolDetails',
            fields=[
                ('enrol_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=True, max_length=50)),
                ('student_contact_no', models.IntegerField()),
                ('course_name', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='student.StudentRegisterModel')),
            ],
        ),
    ]
