# Generated by Django 2.2.12 on 2020-07-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentenroldetails',
            name='course_name',
            field=models.CharField(default=True, max_length=60),
        ),
    ]
