# Generated by Django 2.2.12 on 2020-07-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEnrolDetails',
            fields=[
                ('enrol_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_contact_no', models.IntegerField()),
                ('course_name', models.CharField(max_length=30)),
            ],
        ),
    ]
